abstract class AppStrings{
  static const String appNAme="BANKPICK",
 titleOfOnBoarding1="Fastest Payment in the world",
 titleOfOnBoarding2="The most Secoure Platfrom for Customer",
 titleOfOnBoarding3="The Paying for Everything is Easy and Convenient",
 subtitleOfOnBoarding1="Integrate multiple payment methoods to help you up the process quickly",
 subtitleOfOnBoarding2="Built-in Fingerprint, face recognition and more, keeping you completely safe",
 subtitleOfOnBoarding3="Built-in Fingerprint, face recognition and more, keeping you completely safe",
 next="Next",
signIn=" Sign In",
 signUp=" Sign Up",
emailAddress="Email Address",
password="Password",
changePassword="Change Password",
currentPassword="Current Password",
 newPassword="New Password",
confirmPassword="Confirm New Password",
passwordsMustMatch="Both Passwords Must Match",
termsAndCondition="Terms & Condition",
  textOfTermsAndCondition="L15.1 Thank you for visiting our Application Doctor 24×7 and enrolling as a member."
      "\n\n15.2 Your privacy is important to us. To better protect your privacy, we are providing this notice "
      "explaining our policy with regards to the information you share with us. This privacy policy relates "
      "to the information we collect, online from Application, received through the email, by fax or telephone, "
      "or in person or in any other way and retain and use for the purpose of providing you services. If you do "
      "not agree to the terms in this Policy, we kindly ask you not to use these portals and/or sign the contract document.\n\n15.3 In order to use the services of this "
      "Application, You are required to register yourself by verifying the authorised device."
      " This Privacy Policy applies to your information that we collect and receive on and through Doctor 24×7;"
      " it does not apply to practices of businesses that we do not own or control or people we do not employ."
      "\n\n15.4 By using this Application, you agree to the terms of this Privacy Policy.",
newUser= "I’m a new user.",
fullName="Full Name",
phoneNumber="Phone Number",
alreadyAccount="Already have an account.",
welcome="Welcome back",
userName="Tanya Myroniuk",
job="Senior Designer",
 profile="Profile",
 editProfile="Edit Profile",
personalInformation="Personal Information",
paymentPreferences="Payment Preferences",
bankSandCards="Banks and Cards",
notifications="Notifications",
messageCenter="Message Center",
address="Address",
settings="Settings",
 language="Language",
myProfile="My Profile",
 contactUs="Contact Us",
general="General",
security="Security",
quetionShare="Choose what data you share with us",
privacyPolicy="Privacy Policy",
 biometric="Biometric",
statistics="Statistics",
myCards="My Cards",
addNewCard="Add New Card",
transaction="Transaction",
 currentBalance="Current Balance",
 english="English",
transactionHistory="Transaction History",
monthlySpendingLimit="Monthly spending limit",
      cardholderName="Cardholder Name",
  cVV="4-digit CVV",
cardNumber="Card Number",
 allCards="All Cards",
 addCard="Add Card",
today="Today",
seeAll="See All",
birthDate="Birth Date",
payerName="Payer Name",
description="Description",
 monthlyDueBy="Monthly Due By",
requestMoney="Request Money",
changeCurrency="Change Currency?",
usd="USD",
 australia="Australia",
franch="Franch",
 spanish="Spanish",
 america="America",
vietnam="Vietnam",
 sendMoney="Send Money",
enterYourAmount="Enter Your Amount",
expiryDate="Expiry Date";


}
