///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();
  static const String imagesLogo = 'assets/images/logo.png';
  static const String imagesOnboarding1 = 'assets/images/onboarding1.png';
  static const String imagesOnboarding2 = 'assets/images/onboarding2.png';
  static const String imagesOnboarding3 = 'assets/images/onboarding3.png';
  static const String logoProfile = 'assets/images/logoProfile.png';
  static const String email=" assets/images/email.svg" ;
  static const String chip="assets/images/Chip.svg";
  static const String libMain = 'lib/main.dart';
  static const String routesAppRouter = 'lib/core/routes/app_router.dart';
  static const String utilsAppAssets = 'lib/core/utils/app_assets.dart';
  static const String utilsAppColors = 'lib/core/utils/app_colors.dart';
  static const String utilsAppConstants = 'lib/core/utils/app_constants.dart';
  static const String utilsAppFunctions = 'lib/core/utils/app_functions.dart';
  static const String utilsAppStrings = 'lib/core/utils/app_strings.dart';
  static const String viewsSplashView = 'lib/feautures/splach/presentation/views/splash_view.dart';

}
